// Mocks generated by Mockito 5.4.4 from annotations
// in formularios_front/test/app/domain/widgets/form_card_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:formularios_front/app/domain/entities/form_entity.dart' as _i2;
import 'package:formularios_front/app/domain/entities/section_entity.dart'
    as _i6;
import 'package:formularios_front/app/domain/enum/form_status_enum.dart' as _i5;
import 'package:formularios_front/app/domain/enum/priority_enum.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [FormEntity].
///
/// See the documentation for Mockito's code generation for more information.
class MockFormEntity extends _i1.Mock implements _i2.FormEntity {
  MockFormEntity() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get idExternForm => (super.noSuchMethod(
        Invocation.getter(#idExternForm),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#idExternForm),
        ),
      ) as String);

  @override
  String get idInternForm => (super.noSuchMethod(
        Invocation.getter(#idInternForm),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#idInternForm),
        ),
      ) as String);

  @override
  String get idCreatorUser => (super.noSuchMethod(
        Invocation.getter(#idCreatorUser),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#idCreatorUser),
        ),
      ) as String);

  @override
  String get userId => (super.noSuchMethod(
        Invocation.getter(#userId),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#userId),
        ),
      ) as String);

  @override
  List<String> get idCoordinator => (super.noSuchMethod(
        Invocation.getter(#idCoordinator),
        returnValue: <String>[],
      ) as List<String>);

  @override
  String get templateName => (super.noSuchMethod(
        Invocation.getter(#templateName),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#templateName),
        ),
      ) as String);

  @override
  String get area => (super.noSuchMethod(
        Invocation.getter(#area),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#area),
        ),
      ) as String);

  @override
  String get system => (super.noSuchMethod(
        Invocation.getter(#system),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#system),
        ),
      ) as String);

  @override
  String get street => (super.noSuchMethod(
        Invocation.getter(#street),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#street),
        ),
      ) as String);

  @override
  String get city => (super.noSuchMethod(
        Invocation.getter(#city),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#city),
        ),
      ) as String);

  @override
  int get number => (super.noSuchMethod(
        Invocation.getter(#number),
        returnValue: 0,
      ) as int);

  @override
  double get lat => (super.noSuchMethod(
        Invocation.getter(#lat),
        returnValue: 0.0,
      ) as double);

  @override
  double get long => (super.noSuchMethod(
        Invocation.getter(#long),
        returnValue: 0.0,
      ) as double);

  @override
  String get region => (super.noSuchMethod(
        Invocation.getter(#region),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#region),
        ),
      ) as String);

  @override
  _i4.PriorityEnum get priority => (super.noSuchMethod(
        Invocation.getter(#priority),
        returnValue: _i4.PriorityEnum.LOW,
      ) as _i4.PriorityEnum);

  @override
  _i5.FormStatusEnum get status => (super.noSuchMethod(
        Invocation.getter(#status),
        returnValue: _i5.FormStatusEnum.NAO_INICIADO,
      ) as _i5.FormStatusEnum);

  @override
  int get expiration => (super.noSuchMethod(
        Invocation.getter(#expiration),
        returnValue: 0,
      ) as int);

  @override
  int get dateCreation => (super.noSuchMethod(
        Invocation.getter(#dateCreation),
        returnValue: 0,
      ) as int);

  @override
  List<_i6.SectionEntity> get sections => (super.noSuchMethod(
        Invocation.getter(#sections),
        returnValue: <_i6.SectionEntity>[],
      ) as List<_i6.SectionEntity>);
}
